### ISSUE TITLE
ReLU is not differentiable

### ISSUE THREAD

**Issue by norsimon** [kreshuklab/teaching-dl-course-2019#1]
In Video 2, at around minute 9.
Activation functions are introduced and the two requirements (differentiable and nonlinear) given. 
Sigmod and ReLU shown as examples.
But *ReLU is not differentiable everywhere*.
Perhaps say a word about this or link to somewhere, e.g. 

https://medium.com/@kanchansarkar/relu-not-a-differentiable-function-why-used-in-gradient-based-optimization-7fef3a4cecec

Thanks,
Simon

**Comment by vzinche** [comment]
@akreshuk could you maybe add it as a commend in the video description on youtube?

**Comment by norsimon** [comment]
I added a comment in Video 2. And a bunch of smaller comments to where I thought the slides were incorrect: 
<img width="848" alt="Screenshot 2020-01-06 at 16 48 40" src="https://user-images.githubusercontent.com/4386747/71829243-7c83be80-30a4-11ea-959b-14952a5f3238.png">

**Comment by vzinche** [comment]
Thank you, Simon!
