### ISSUE TITLE
Small image display

### ISSUE THREAD

**Issue by tischi** [kreshuklab/teaching-dl-course-2019#4]
https://github.com/kreshuklab/teaching-dl-course-2019/blob/master/Webinars/exercise1/image_manipulation.ipynb?short_path=a1d32b1#L385

Doing this results for me in very small images; it is hard to see anything.
For me, it is better to use two times `cv2_imshow`.

**Comment by constantinpape** [comment]
Have you tried using the matplotlib functionality instead?
In general, I would discourage using the openCv python bindings, the combination of skimage
and matplotlib is easier to set up and much more common in the python image analysis community.

**Comment by vzinche** [comment]
Yes, we're switching to matplotlib afterwards. I just wanted to generally show them what you can do with images, but thanks, I didn't know what's more common. I wouldn't change the library now (the exercises were sent off like 4 days ago already), but we'll consider it for the next year
