### ISSUE TITLE
1/N => 1/2

### ISSUE THREAD

**Issue by tischi** [kreshuklab/teaching-dl-course-2019#6]
https://github.com/kreshuklab/teaching-dl-course-2019/blob/master/Webinars/exercise1/image_manipulation.ipynb?short_path=a1d32b1#L423

This should say `1/2` of the image dimensions and not `1/N`.

**Comment by vzinche** [comment]
why 2? it should work for any N given as a function argument here, 2 was just an example

**Comment by tischi** [comment]
ok!
