### ISSUE TITLE
threshold is confusing

### ISSUE THREAD

**Issue by tischi** [kreshuklab/teaching-dl-course-2019#9]
https://github.com/kreshuklab/teaching-dl-course-2019/blob/master/Webinars/exercise1/image_manipulation.ipynb?short_path=a1d32b1#L497

I find this quite confusing. Maybe easier to understand like this?

```
# pixels below the threshold (background) will be set to 0
# pixels above or equal to the threshold (foreground) will be set to the given foreground value, typically 1
threshold = 150
foreground = 1 # value of foreground pixels in resulting binary image
inverted_image = (image.max() - image) # in our example image the objects are dark, thus we invert before we threshold
_, binary_thresholded_image = cv2.threshold(inverted_image, threshold, foreground, cv2.THRESH_BINARY)
show_two_images(inverted_image, binary_thresholded_image)
```

**Comment by vzinche** [comment]
Can you make a pull request with this? Just for the sake of getting credits for your code

**Comment by tischi** [comment]
I can do this, but I thought it is easier if you change it for you.

**Comment by vzinche** [comment]
It is easier, but if you are contributing be on the contributors list as well :)
